defaults:
  profile: "default"

profiles:
  default:
    extraction:
      embedding_models: ["Facenet512"]

  multi_embedding_balanced:
    extraction:
      embedding_models: ["Facenet512", "VGG-Face", "DeepID"]

  deepid_fast:
    extraction:
      embedding_models: ["DeepID"]

  debug_loose:
    extraction:
      embedding_models: ["Facenet512"]
